[workspace]
members = [
    "serde-query",
    "serde-query-core",
    "serde-query-derive",
]

[workspace.dependencies]
proc-macro2 = "1.0.51"
syn = "1.0.107"
quote = "1.0.23"
proc-macro-error = "1.0.4"
